# Generated by Django 4.0 on 2022-01-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "ordering": ["-datatime"],
                "verbose_name": "страница",
                "verbose_name_plural": "страницы",
            },
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=models.TextField(blank=True, verbose_name="Контент"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="datatime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликованно?"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="photos/%Y/%m/%d/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
